### ISSUE TITLE
请问secret.json文件在哪里呢，我找不到

### ISSUE THREAD

**Issue by zjrwtx** [dy-xiaodong2022/wechat-robot#1]
![image](https://user-images.githubusercontent.com/86822589/209688076-a52a0bdb-caf3-4187-bc3c-6cb2adf3f512.png)

**Comment by xiaodong2008** [comment]
这个需要自己创建

**Comment by xiaodong2008** [comment]
创建的内容请看index.ts，里面有提到secret.json的内容都有什么

**Comment by xiaodong2008** [comment]
README更新了，你可以看一下，我放了secret.json的格式

**Comment by zjrwtx** [comment]
收到 谢谢！
